services:
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - 'frontend'
      - 'backend'
    container_name: reverse-proxy
  frontend:
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_BACKEND_URL=/api/
    volumes:
      - ./todo-frontend:/usr/src/app
  backend:
    build: 
      context: ./todo-backend
      dockerfile: Dockerfile
    volumes:
      - ./todo-backend:/usr/src/app
    environment: 
      - NODE_ENV=production
      - REDIS_URL=//redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
